language: ruby
rbenv:
  - 3.0.1
services:
  - postgresql
script:
  - bundle install
  - bundle exec rails db:environment:set RAILS_ENV=test
  - bundle exec rails db:{create,migrate,seed} RAILS_ENV=test
  - bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: a9cefd419bccf1dbc85bdafd3af640b77d7f9f144aae7797306ec480c9acc7362ca5771c8f8522882bd2921a2117063e26173f93a24d524380491d9534c8a5ab
  app: beatfolio
  on:
    repo: beatfolio
    branch: main
notifications:
  email:
    on_success: never
    on_failure: never
cache:
  - bundler