language: ruby
rbenv:
- 3.0.1
services:
  - postgresql
script:
- bundle exec rails db:{create,migrate,seed} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure:
  app: beatfolio
  on:
    repo: beatfolio
    branch: main
notifications:
  email:
    on_success: never
    on_failure: never
cache:
- bundler