language: ruby
rbenv:
- 3.0.1
services:
- postgresql
script:
- bundle install
- npm install
- bundle exec rails db:{create,migrate,seed} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: BX4q8AsGHlRsXP5/xJn71+xebqEPXVO0gkjmJDZkUu7+9NnF47xy3V1D9gvI2sVl4aVc5SC1cuQSxfT67+8y7ZcmP5d/TOcHz3GXDz2zvplTLqrj77Q3/AILz1+wK8WMpS+BOoX/NvtGKiue4HtiS7MMt1+JAK7alBdec+djYC4fddX1qEbw3q4+dWCQvIRwGatrZnw0fhrk2YOYeKvNCo/8Yws8oLQPR0dxrxbXedGiMdxH6i8i6RjJ54U9berop4nAjxcqOfLTEt/CONv+His/cGA/fXR0EtjplHZAFb/1Grzwa7Av0zCCHpVC9/OKaWYss/E8Pr+WnH5HKViecmh+c3b5dLPDErZ+nlwRmgqRT/JjAagfeWyTNjD6TlFcQC5NVEj/RYtCgK0EajbKsfgidyt8RDwGgb38ix+ui1CqTL4GvR7sxrbljE6Rz4CtUw3KftbKL5pcE6vf9y0eaxdGqdDdeLTFNJEX1emeP6uaey5kv/puk6fmSIztbxQ0pcWJYMTpow+m5pTktVxw3jx5ryNq2hsN04eLir0/ZHqELjaTCqzJ7o5Y8QXE5aqvcDzj7/ETNjB5freh7/p8EyTFJ31pmxp6FEePdpcXIMTr0bwydKg2V/Lp2iYTYDglAXLiFTUjQFCm00s2pWR8TKHZvMqyxka16QcFxfYChYU=
  app: beatfolio
  on:
    repo: lkriffell/beatfolio
    branch: main
notifications:
  email:
    on_success: never
    on_failure: never
cache:
- bundler
