language: ruby
rbenv:
  - 3.0.1
services:
  - postgresql
script:
  - bundle install
  - npm install
  - bundle exec rails db:{create,migrate,seed} RAILS_ENV=test
  - bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: CPkqHTjLFTXD/ZQvXynudpn6vdwy/GXyFzLQoGKCsgjVkFPBxxsMMHPMhJXTvXjAestih/qNUW7EQE11UdkcS2vmsp1GXmwGUNzO1nisGS0qN0yGeYedccTOWwvugPLIXim5CuGeYsGGWLp6tCtc0oS3kjrVZmOSBX14bPjiRZ7Jy/5O5sgdv7E1kauFyhVNs+P5HlbGDOY6o2gcM9XUKWCmflt3x7Lv3QMQaXQKHcRpcBfDZxpzuMiPwooXEbUj0OpfHZhrnntiN3QL7/QexL6LuLpoIdUmOqcgUp72o7KmHYZescjVzKIBbvgCswZKtdeFoTRJu8Y+127RXdE28a9b2gBIKP6bI8ntWcALQ0PWEufGnekTpd3kSeDdsr0ku/DEzenMb98graCqDNdRu7DEXD5t+9QNWIiPJzU8tdnZAPOWz5qvl1Rd+aXOecMFUPMgsl2xLhMgUdegj+HnNeOd6OQowag9s5JN5x+SnqWnQva+Ai8FxtwkmqYVBqrVOc7etIic9CeVE+Uk5bmzZeHBQOeeSmI2x0VOZQEtQ9D/IeTPqEfH9DNVyi1wYuWeNEtuuer99XuRoBPrGgbMU1Ecpapjz1POjQfAMAjXy6wFte1V/HpnTijDULGViiAKoL53wMzoUascf1j2eeyLw/UAexAlywNcq0g+vuZP5CM=
  app: beatfolio
  on:
    repo: lkriffell/beatfolio
    branch: main
notifications:
  email:
    on_success: never
    on_failure: never
cache:
  - bundler