language: ruby
rbenv:
  - 3.0.1
services:
  - postgresql
script:
  - bundle install
  - npm install
  - bundle exec rails db:{create,migrate,seed} RAILS_ENV=test
  - bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: jm+VNqpgJZYpHervFNN+PHlvx+1EM5+fkG3Va7fXfv0/oxslVSASgGv8bTlNOmkjStYhHGY3GzqGeuB1jKzM8+xkxCZ+cA2cIwcyOqH6+mrfTqLxs8aD9qb80v/aJFNQBgL5L3KBufi2RW1VQf7tQ04bzv1mjlt4IVx063fjazoyjbKdMKwtX5n6TljPYnO2G1mHDkM4quvw5YCvdGULmUiUwG7Ld9Ybi7CW9URTxcdtk2DT5dUzgKcl3CiKcn8AWI1dMQxxqsQcJ785Cdq4chUtcieplyPGS2qIXULd63cg3yU5V82of9tpLOMvySq0MmIb4FHpqCN50x/I/fUlQLa8h4ClRHzbEWYRe+kjDliNToFQIkwCJpKJ2xoiAniv3fpT0dOVjHqR90yE1GJ6nNY3J/uxgvLZ3Zvo9Y/TPOsbisxCATDyiBXNoQhljGwMuHVVjHn3uMsIj4phgfgC7ri7fFahra/L/f4iNncf3aEY6QR1x09cOBVYo2Ar9Wc6ZwY99MlZ3OjBwqQ34fG9MEiwDjXa87rB+i/jNx0suLwLhKR4i4/lGeYCAWblwDwWN02DasWYU64H+x6qVO3993vn+Rb36T7unipLdx3hAmA/DHhz/vd88IjFPa/IECb9gGkJSHs5l8uq7x37N497pDWmaqzhWkUtTRx9lBTWJtM=
  app: beatfolio
  on:
    repo: lkriffell/beatfolio
    branch: main
notifications:
  email:
    on_success: never
    on_failure: never
cache:
  - bundler